name: Realistic GitHub Activity

on:
  schedule:
    # Monday - 20 commits
    - cron: '0 0 * * 1'
    - cron: '10 0 * * 1'
    - cron: '20 0 * * 1'
    - cron: '30 0 * * 1'
    - cron: '40 0 * * 1'
    - cron: '50 0 * * 1'
    - cron: '0 1 * * 1'
    - cron: '10 1 * * 1'
    - cron: '20 1 * * 1'
    - cron: '30 1 * * 1'
    - cron: '40 1 * * 1'
    - cron: '50 1 * * 1'
    - cron: '0 2 * * 1'
    - cron: '10 2 * * 1'
    - cron: '20 2 * * 1'
    - cron: '30 2 * * 1'
    - cron: '40 2 * * 1'
    - cron: '50 2 * * 1'
    - cron: '0 3 * * 1'
    - cron: '10 3 * * 1'

    # Tuesday - 14 commits
    - cron: '0 0 * * 2'
    - cron: '10 0 * * 2'
    - cron: '20 0 * * 2'
    - cron: '30 0 * * 2'
    - cron: '40 0 * * 2'
    - cron: '50 0 * * 2'
    - cron: '0 1 * * 2'
    - cron: '10 1 * * 2'
    - cron: '20 1 * * 2'
    - cron: '30 1 * * 2'
    - cron: '40 1 * * 2'
    - cron: '50 1 * * 2'
    - cron: '0 2 * * 2'
    - cron: '10 2 * * 2'

    # Wednesday - 12 commits
    - cron: '0 0 * * 3'
    - cron: '10 0 * * 3'
    - cron: '20 0 * * 3'
    - cron: '30 0 * * 3'
    - cron: '40 0 * * 3'
    - cron: '50 0 * * 3'
    - cron: '0 1 * * 3'
    - cron: '10 1 * * 3'
    - cron: '20 1 * * 3'
    - cron: '30 1 * * 3'
    - cron: '40 1 * * 3'
    - cron: '50 1 * * 3'

    # Thursday - 22 commits
    - cron: '0 0 * * 4'
    - cron: '10 0 * * 4'
    - cron: '20 0 * * 4'
    - cron: '30 0 * * 4'
    - cron: '40 0 * * 4'
    - cron: '50 0 * * 4'
    - cron: '0 1 * * 4'
    - cron: '10 1 * * 4'
    - cron: '20 1 * * 4'
    - cron: '30 1 * * 4'
    - cron: '40 1 * * 4'
    - cron: '50 1 * * 4'
    - cron: '0 2 * * 4'
    - cron: '10 2 * * 4'
    - cron: '20 2 * * 4'
    - cron: '30 2 * * 4'
    - cron: '40 2 * * 4'
    - cron: '50 2 * * 4'
    - cron: '0 3 * * 4'
    - cron: '10 3 * * 4'
    - cron: '20 3 * * 4'
    - cron: '30 3 * * 4'

    # Friday - 10 commits
    - cron: '0 0 * * 5'
    - cron: '10 0 * * 5'
    - cron: '20 0 * * 5'
    - cron: '30 0 * * 5'
    - cron: '40 0 * * 5'
    - cron: '50 0 * * 5'
    - cron: '0 1 * * 5'
    - cron: '10 1 * * 5'
    - cron: '20 1 * * 5'
    - cron: '30 1 * * 5'

    # Saturday - 8 commits
    - cron: '0 0 * * 6'
    - cron: '10 0 * * 6'
    - cron: '20 0 * * 6'
    - cron: '30 0 * * 6'
    - cron: '40 0 * * 6'
    - cron: '50 0 * * 6'
    - cron: '0 1 * * 6'
    - cron: '10 1 * * 6'

    # Sunday - 6 commits
    - cron: '0 0 * * 0'
    - cron: '10 0 * * 0'
    - cron: '20 0 * * 0'
    - cron: '30 0 * * 0'
    - cron: '40 0 * * 0'
    - cron: '50 0 * * 0'

  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Random File and Message
        run: |
          messages=("fix: update logs" "feat: add new entry" "docs: update file" "chore: maintenance task" "refactor: improve structure")
          commit_msg=${messages[$RANDOM % ${#messages[@]}]}
          files=("log.txt" "readme.md" "notes.txt" "daily.md" "progress.txt")
          file_name=${files[$RANDOM % ${#files[@]}]}
          echo "Updated on $(date)" >> "$file_name"
          echo "COMMIT_MSG=$commit_msg" >> $GITHUB_ENV
          echo "FILE_NAME=$file_name" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config --global user.name "sehrishkhalid1"
          git config --global user.email "dev.sehrishkhalid01@gmail.com"
          git pull origin main --rebase || echo "No changes to pull"
          git add "$FILE_NAME"
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push https://sehrishkhalid1:${{ secrets.GH_PAT }}@github.com/sehrishkhalid1/DoK-Wallet.git
